# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedPathHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedPathHelpersModule`.


module GeneratedPathHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def absorb_api_entry_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_entries_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_entry_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_feedbacks_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_me_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_session_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_todo_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_todos_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_users_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def fork_api_entry_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def lift_api_entry_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_health_check_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def restore_api_entry_path(*args); end

  sig { params(args: T.untyped).returns(String) }
  def tree_api_entry_path(*args); end
end
