# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpersModule`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpersModule`.


module GeneratedUrlHelpersModule
  include ::ActionDispatch::Routing::UrlFor
  include ::ActionDispatch::Routing::PolymorphicRoutes

  sig { params(args: T.untyped).returns(String) }
  def absorb_api_entry_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_entries_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_entry_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_me_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_session_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_todo_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_todos_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def api_users_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def fork_api_entry_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def lift_api_entry_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_health_check_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_notes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_properties_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_routes_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_info_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def rails_mailers_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def restore_api_entry_url(*args); end

  sig { params(args: T.untyped).returns(String) }
  def tree_api_entry_url(*args); end
end
